const STORAGE_KEY = 'mini-basketball-scorebook-v3';
const ACTIONS = {
  FTM:{label:'FT成功',points:1},FTX:{label:'FT失敗',points:0},'2PM':{label:'2P成功',points:2},'2PX':{label:'2P失敗',points:0},'3PM':{label:'3P成功',points:3},'3PX':{label:'3P失敗',points:0},
  OREB:{label:'オフェンスリバウンド',points:0},DREB:{label:'ディフェンスリバウンド',points:0},AST:{label:'アシスト',points:0},TOV:{label:'ターンオーバー',points:0},STL:{label:'スティール',points:0},BLK:{label:'ブロック',points:0},PF:{label:'ファウル',points:0},TIMEOUT:{label:'TIMEOUT',points:0},PERIOD_CHANGE:{label:'クォーター変更',points:0}
};
const initialPlayers=()=>Array.from({length:5},(_,i)=>({id:`p-${i+1}-${Math.random().toString(36).slice(2)}`,number:String(i+4),name:`PLAYER ${i+1}`,license:'',periods:[null,null,null,null]}));
const defaultState=()=>({version:3,period:1,seconds:360,running:false,possession:null,selected:null,tournament:'U12 SPRING CUP',gameDate:new Date().toISOString().slice(0,10),gameTime:'',venue:'',gameNo:'',crewChief:'',umpire:'',scorer:'',timer:'',assistantScorer:'',shotClockOperator:'',endTime:'',playersA:initialPlayers(),playersB:initialPlayers(),teamAName:'SKY HAWKS',teamBName:'RED COMETS',events:[],future:[],activeView:'input'});
function createPeriodChangeEvent(state,id=`${Date.now()}-${Math.random()}`){const toPeriod=state.period+1;return{id,action:'PERIOD_CHANGE',period:state.period,time:formatTime(state.seconds),team:null,playerId:null,fromPeriod:state.period,toPeriod,fromSeconds:state.seconds,toSeconds:toPeriod<=4?360:180};}
function createEvent(state,team,playerId,action,id=`${Date.now()}-${Math.random()}`){if(!ACTIONS[action]||!['A','B'].includes(team))throw Error('Invalid event');if(action!=='TIMEOUT'&&!state[`players${team}`].some(p=>p.id===playerId))throw Error('Player not found');return{id,period:state.period,time:formatTime(state.seconds),team,playerId:playerId||null,action};}
function derive(state){
 const stats={A:{},B:{}},scores={A:0,B:0},quarterScores={A:[0,0,0,0,0],B:[0,0,0,0,0]},teamFoulsByPeriod={A:[],B:[]},timeouts={A:[0,0,0,0,0],B:[0,0,0,0,0]},running=[],pbp=[],endedPeriods=[],activePeriods=new Set();let a=0,b=0;
 ['A','B'].forEach(t=>state[`players${t}`].forEach(p=>stats[t][p.id]={PTS:0,FTM:0,FTA:0,'2PM':0,'2PA':0,'3PM':0,'3PA':0,OREB:0,DREB:0,REB:0,AST:0,TOV:0,STL:0,BLK:0,PF:0,personalFouls:[]}));
 state.events.forEach(event=>{const act=ACTIONS[event.action];if(!act)return;if(event.action==='PERIOD_CHANGE'){endedPeriods.push(event.fromPeriod);pbp.push({...event,displayPeriod:event.fromPeriod,time:event.time,label:`${periodLabel(event.fromPeriod)}終了`,points:0,scoreA:a,scoreB:b,system:true});pbp.push({...event,displayPeriod:event.toPeriod,time:formatTime(event.toSeconds),label:`${periodLabel(event.toPeriod)}開始`,points:0,scoreA:a,scoreB:b,system:true});return;}activePeriods.add(event.period);if(event.action==='TIMEOUT'){timeouts[event.team][Math.min(event.period,5)-1]++;pbp.push({...event,label:act.label,points:0,scoreA:a,scoreB:b});return;}const s=stats[event.team][event.playerId];if(!s)return;const points=act.points;
  if(event.action==='FTM'){s.FTM++;s.FTA++;}if(event.action==='FTX')s.FTA++;if(event.action==='2PM'){s['2PM']++;s['2PA']++;}if(event.action==='2PX')s['2PA']++;if(event.action==='3PM'){s['3PM']++;s['3PA']++;}if(event.action==='3PX')s['3PA']++;if(['OREB','DREB','AST','TOV','STL','BLK','PF'].includes(event.action))s[event.action]++;if(event.action==='PF'){s.personalFouls.push(event.period);teamFoulsByPeriod[event.team][event.period-1]=(teamFoulsByPeriod[event.team][event.period-1]||0)+1;}
  s.PTS+=points;s.REB=s.OREB+s.DREB;scores[event.team]+=points;quarterScores[event.team][Math.min(event.period,5)-1]+=points;if(event.team==='A')a+=points;else b+=points;const player=state[`players${event.team}`].find(p=>p.id===event.playerId);const detail={...event,player,label:act.label,points,scoreA:a,scoreB:b};pbp.push(detail);if(points)running.push(detail);
 });
 return{stats,scores,quarterScores,teamFoulsByPeriod,timeouts,running,pbp,endedPeriods,activePeriods:[...activePeriods],currentPeriod:state.period,gameEnded:Boolean(state.endTime),teamFouls:{A:teamFoulsByPeriod.A[state.period-1]||0,B:teamFoulsByPeriod.B[state.period-1]||0}};
}
function formatTime(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}function periodLabel(p){return p<=4?`${p}Q`:p===5?'OT':`OT${p-4}`;}function getQuarterRecordColor(quarter){return quarter===1||quarter===3?'red':'black';}function periodInkClass(period){return`ink-${getQuarterRecordColor(period)}`;}function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function runningScoreCells(data){const marks={A:{},B:{}};data.running.forEach(e=>{const score=e.team==='A'?e.scoreA:e.scoreB;marks[e.team][score]={event:e};});(data.endedPeriods||[]).forEach(period=>{const last=data.running.filter(e=>e.period===period).at(-1);if(last){const score=last.team==='A'?last.scoreA:last.scoreB;marks[last.team][score].close='period';}});if(data.gameEnded){const last=data.running.at(-1);if(last){const score=last.team==='A'?last.scoreA:last.scoreB;marks[last.team][score].close='game';}}return Array.from({length:3},(_,block)=>`<table class="run-block"><colgroup><col class="scorer-col"><col class="score-col"><col class="score-col team-b-score-number"><col class="scorer-col"></colgroup><thead><tr><th>A</th><th>得点</th><th class="team-b-score-number">得点</th><th>B</th></tr></thead><tbody>${Array.from({length:40},(_,i)=>{const n=block*40+i+1,a=marks.A[n],b=marks.B[n],unusedA=data.gameEnded&&n>data.scores.A,unusedB=data.gameEnded&&n>data.scores.B;return`<tr><td>${scorerMark(a)}</td><th class="running-score team-a-score-number ${periodInk(a)} ${closingClass(a)}">${n}${scoreMark(a)}${unusedMark(unusedA)}</th><th class="running-score team-b-score-number ${periodInk(b)} ${closingClass(b)}">${n}${scoreMark(b)}${unusedMark(unusedB)}</th><td>${scorerMark(b)}</td></tr>`}).join('')}</tbody></table>`).join('');}
function scoreQuarterStack(data){const started=new Set([...(data.endedPeriods||[]),...(data.activePeriods||[])]),currentPeriod=data.currentPeriod||1;const regulation=[0,1,2,3].map(index=>{const played=started.has(index+1);return`<div class="quarter-score-line"><strong>${played?data.quarterScores.A[index]:''}</strong><i>－</i><strong>${played?data.quarterScores.B[index]:''}</strong></div>`;}).join('');const overtimeStarted=currentPeriod>4||(data.endedPeriods||[]).some(period=>period>4);const overtime=overtimeStarted?`<span>（延長）</span><div class="overtime-score"><strong>${data.quarterScores.A[4]}</strong><i>－</i><strong>${data.quarterScores.B[4]}</strong></div>`:'<span>（延長）</span>';return`${regulation}<div class="overtime-line">${overtime}</div>`;}
function participationMark(value){return value===true||value==='in'?'／':value==='out'?'＼':'';}
function participationRecordClass(quarter){return`participation-mark ${periodInkClass(quarter)}`;}
function periodInk(mark){return mark?periodInkClass(mark.event.period):'';}
function closingClass(mark){return mark?.close?`score-close score-close-${mark.close}`:'';}
function scorerMark(mark){if(!mark)return'';const cls=`${periodInk(mark)} ${mark.event.action==='3PM'?'three-point':''} ${mark.close?`score-close score-close-${mark.close}`:''}`;return`<span class="scorer-mark ${cls}" title="${escapeHtml(mark.event.label)}">${escapeHtml(mark.event.player.number)}</span>`;}
function scoreMark(mark){if(!mark)return'';const cls=periodInk(mark);return mark.event.action==='FTM'?`<span class="score-dot ${cls}" aria-label="フリースロー成功">●</span>`:`<span class="score-slash ${cls}" aria-hidden="true"></span>`;}
function unusedMark(unused){return unused?'<span class="unused-score-slash" aria-hidden="true"></span>':'';}
if(typeof module!=='undefined')module.exports={ACTIONS,defaultState,createEvent,createPeriodChangeEvent,derive,formatTime,periodLabel,getQuarterRecordColor,getQuarterInk:getQuarterRecordColor,runningScoreCells,scoreQuarterStack,participationMark,participationRecordClass};
if(typeof document!=='undefined'){
 let state=loadState(),timerId=null,recognition=null,sheetZoomMode='fit';function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem('mini-basketball-scorebook-v2'));if(s)return{...defaultState(),...s,version:3,playersA:s.playersA.map(normalizePlayer),playersB:s.playersB.map(normalizePlayer),running:false};}catch{}return defaultState();}function normalizePlayer(p){const player={license:'',periods:[null,null,null,null],...p};player.periods=player.periods.map(value=>value===true?'in':value===false?null:value);return player;}function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,running:false}));}function byId(id){return document.getElementById(id);}function selectedPlayer(){return state.selected&&state[`players${state.selected.team}`].find(p=>p.id===state.selected.playerId);}function setActiveStatButton(button){if(!button.closest('.stats-actions')||button.classList.contains('foul-action'))return;document.querySelectorAll('.stats-actions [data-action]:not(.foul-action)').forEach(b=>{const active=b===button;b.classList.toggle('stat-active',active);b.setAttribute('aria-pressed',active?'true':'false');});}function addEvent(team,id,action){state.events.push(createEvent(state,team,id,action));state.future=[];render();}
 function render(){const d=derive(state),p=selectedPlayer();byId('scoreA').value=d.scores.A;byId('scoreB').value=d.scores.B;byId('period').textContent=periodLabel(state.period);const next=periodLabel(state.period+1),advance=byId('periodAdvance');advance.innerHTML=state.period<4?`次のクォーターへ <strong>${next}</strong> <span aria-hidden="true">＞</span>`:state.period===4?'延長 <strong>OT</strong> へ <span aria-hidden="true">＞</span>':`次の延長 <strong>${next}</strong> へ <span aria-hidden="true">＞</span>`;advance.setAttribute('aria-label',`${periodLabel(state.period)}を終了して${next}へ進む`);byId('clock').textContent=formatTime(state.seconds);byId('clockToggle').textContent=state.running?'PAUSE':'START';['A','B'].forEach(team=>document.querySelectorAll(`[data-team-name="${team}"]`).forEach(input=>{if(document.activeElement!==input)input.value=state[`team${team}Name`];}));['tournament','gameDate'].forEach(id=>{if(document.activeElement!==byId(id))byId(id).value=state[id];});byId('homeRosterTitle').textContent=state.teamAName;byId('awayRosterTitle').textContent=state.teamBName;byId('teamFoulA').value=d.teamFouls.A;byId('teamFoulB').value=d.teamFouls.B;byId('selectionPrompt').innerHTML=p?`<small>SELECTED PLAYER</small><strong>${state.selected.team==='A'?'HOME':'AWAY'} #${escapeHtml(p.number)} ${escapeHtml(p.name)}</strong>`:'<small>SELECTED PLAYER</small><strong>選手を選択してください</strong>';document.querySelectorAll('[data-action]').forEach(b=>b.disabled=!p);byId('undoButton').disabled=!state.events.length;byId('redoButton').disabled=!state.future.length;document.querySelectorAll('[data-possession]').forEach(b=>b.classList.toggle('active',b.dataset.possession===state.possession));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.activeView));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${state.activeView}View`));renderRoster('A',d);renderRoster('B',d);renderStats(d);renderSheet(d);renderPbp(d);saveState();if(state.activeView==='sheet')requestAnimationFrame(()=>applySheetZoom());}
 function renderRoster(t,d){byId(`roster${t}`).innerHTML=state[`players${t}`].map((p,i)=>`<div class="player-row ${state.selected?.playerId===p.id?'selected':''}" data-select-player="${p.id}" data-team="${t}"><input data-player-field="number" data-team="${t}" data-index="${i}" value="${escapeHtml(p.number)}" aria-label="背番号"><input data-player-field="name" data-team="${t}" data-index="${i}" value="${escapeHtml(p.name)}" aria-label="選手名"><b>${d.stats[t][p.id].PF}</b><div class="period-checks">${[1,2,3,4].map(q=>`<label>${q}Q<select data-period-player="${q}" data-team="${t}" data-index="${i}" aria-label="${q}Q 出場記録"><option value="" ${!p.periods[q-1]?'selected':''}>－</option><option value="in" ${p.periods[q-1]===true||p.periods[q-1]==='in'?'selected':''}>／ 出場</option><option value="out" ${p.periods[q-1]==='out'?'selected':''}>＼ 交代退場</option></select></label>`).join('')}</div></div>`).join('');}
 function statTable(t,d){return`<section class="stat-card"><h2><i>${t==='A'?'HOME':'AWAY'}</i> ${escapeHtml(state[`team${t}Name`])}</h2><div class="table-wrap"><table><thead><tr><th>NO.</th><th>PLAYER</th>${['PTS','FTM/A','2PM/A','3PM/A','OREB','DREB','REB','AST','TOV','STL','BLK','PF'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${state[`players${t}`].map(p=>{const s=d.stats[t][p.id];return`<tr><td>${escapeHtml(p.number)}</td><td>${escapeHtml(p.name)}</td><td>${s.PTS}</td><td>${s.FTM}/${s.FTA}</td><td>${s['2PM']}/${s['2PA']}</td><td>${s['3PM']}/${s['3PA']}</td>${['OREB','DREB','REB','AST','TOV','STL','BLK','PF'].map(k=>`<td>${s[k]}</td>`).join('')}</tr>`}).join('')}</tbody></table></div></section>`;}function renderStats(d){byId('statsContent').innerHTML=statTable('A',d)+statTable('B',d);}
 function sheetTeam(t,d){const list=[...state[`players${t}`],...Array(Math.max(0,15-state[`players${t}`].length)).fill(null)].slice(0,15);return`<section class="official-team team-${t}"><div class="team-band"><div><b><span>チーム${t}:</span> <em class="sheet-team-name">${escapeHtml(state[`team${t}Name`])}</em></b><small>Team ${t}</small></div><strong>（${t==='A'?'白':'　'}）</strong><div class="sheet-timeouts"><span>タイムアウト</span><div>${['①','②','③','④','OT'].map((q,i)=>`<i class="${d.timeouts[t][i]?'used':''}">${q}${d.timeouts[t][i]?`<b>${d.timeouts[t][i]}</b>`:''}</i>`).join('')}</div></div></div><table class="players-table"><colgroup><col class="row-no"><col class="license"><col class="player-name"><col class="uniform"><col span="4" class="period-col"><col span="5" class="foul-col"></colgroup><thead><tr><th rowspan="2">No.</th><th rowspan="2">ライセンスNo.</th><th rowspan="2">選手氏名<small>Players</small></th><th rowspan="2">No.</th><th colspan="4">出 場 時 限</th><th colspan="5">ファウル</th></tr><tr>${['①','②','③','④'].map(x=>`<th>${x}</th>`).join('')}${[1,2,3,4,5].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${list.map((p,i)=>`<tr><td>${i+1}</td><td>${p?`<input maxlength="3" inputmode="numeric" aria-label="チーム${t} ${i+1}番 ライセンスNo." data-player-field="license" data-team="${t}" data-index="${i}" value="${escapeHtml(p.license)}">`:''}</td><td>${p?escapeHtml(p.name):''}</td><td>${p?escapeHtml(p.number):''}</td>${[0,1,2,3].map(q=>`<td class="${participationRecordClass(q+1)}">${p?participationMark(p.periods[q]):''}</td>`).join('')}${[1,2,3,4,5].map(n=>`<td>${p&&d.stats[t][p.id].personalFouls[n-1]?`<span class="${periodInkClass(d.stats[t][p.id].personalFouls[n-1])}">×</span>`:''}</td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr><th colspan="2">コーチ:</th><td colspan="11"></td></tr><tr><th colspan="2">A.コーチ:</th><td colspan="11"></td></tr></tfoot></table></section>`;}
 function teamFoulBox(t,d){return`<section class="sheet-team-fouls fouls-${t}"><h3>チーム<br>ファウル</h3>${[[0,1],[2,3]].map(pair=>`<table><thead><tr>${pair.map(q=>`<th>${q+1}Q</th>`).join('')}</tr></thead><tbody>${[1,2,3,4].map(n=>`<tr>${pair.map(q=>`<td class="${d.teamFoulsByPeriod[t][q]>=n?`marked ${periodInkClass(q+1)}`:''}">${n}</td>`).join('')}</tr>`).join('')}</tbody></table>`).join('')}</section>`;}
 function metaInput(key,label,type='text'){return`<label><span class="meta-label">${label}</span><input type="${type}" data-meta="${key}" value="${escapeHtml(state[key])}"></label>`;}
 function renderSheet(d){const winner=d.scores.A===d.scores.B?'引き分け':state[d.scores.A>d.scores.B?'teamAName':'teamBName'];byId('scoreSheet').innerHTML=`<header class="official-title"><b>JBA U12</b><h1>MINI-BASKETBALL&nbsp; OFFICIAL&nbsp; SCORESHEET</h1></header><section class="official-sheet-header" aria-label="大会・試合情報"><div class="header-left"><div class="competition-row">${metaInput('tournament','大会名')}</div><div class="official-score-box" aria-label="スコア"><div class="score-label-col"><b>スコア</b><span>Score</span></div><div class="score-summary"><div class="team-total"><span>チームA</span><strong aria-label="チームA 合計得点">${d.scores.A}</strong></div><div class="score-quarter-stack" aria-label="クォーター別得点">${scoreQuarterStack(d)}</div><div class="team-total"><span>チームB</span><strong aria-label="チームB 合計得点">${d.scores.B}</strong></div></div></div></div><div class="header-right"><div class="match-info"><div class="date-time">${metaInput('gameDate','日付　　年　　月　　日','date')}${metaInput('gameTime','時間　　：','time')}</div><div class="venue-game">${metaInput('venue','会場')}${metaInput('gameNo','Game No.')}</div></div><div class="officials-grid">${metaInput('crewChief','クルーチーフ')}${metaInput('umpire','アンパイア')}${metaInput('scorer','スコアラー')}${metaInput('timer','タイマー')}${metaInput('assistantScorer','A.スコアラー')}${metaInput('shotClockOperator','ショットクロックオペレーター')}</div></div></section><div class="sheet-body"><div class="teams-column">${sheetTeam('A',d)}${sheetTeam('B',d)}<small class="sheet-note">※ライセンスNo.とは、JBA登録番号（メンバーID）の下3桁を記入してください。</small></div><div class="fouls-column">${teamFoulBox('A',d)}${teamFoulBox('B',d)}</div><section class="official-running"><h2>ランニング スコア　<small>RUNNING SCORE</small></h2><div class="running-columns">${runningScoreCells(d)}</div></section></div><section class="result"> <div><b>勝利チーム</b><strong>${escapeHtml(winner)}</strong></div><div><b>試合終了時間</b>${metaInput('endTime','', 'time')}</div></section><small class="sheet-credit">公益財団法人日本バスケットボール協会</small>`;}
 function renderPbp(d){byId('pbpContent').innerHTML=d.pbp.length?[...d.pbp].reverse().map(e=>{const teamName=e.team?state[`team${e.team}Name`]:'';return`<article class="${e.system?'system-event':''}"><time>${periodLabel(e.displayPeriod||e.period)}<b>${e.time}</b></time>${e.system?'<span class="event-marker">Q</span>':`<span class="team-badge ${e.team}">TEAM ${e.team}</span>`}<div><strong>${e.player?`#${escapeHtml(e.player.number)} ${escapeHtml(e.player.name)}`:e.system?'GAME':`TEAM ${e.team} ${escapeHtml(teamName)}`}</strong><small>${e.label}</small></div><output>${e.scoreA} - ${e.scoreB}</output></article>`;}).join(''):'<div class="empty">まだ記録がありません</div>';}
 function showToast(m){const t=byId('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}document.addEventListener('click',e=>{const tab=e.target.closest('[data-view]');if(tab){state.activeView=tab.dataset.view;render();return;}const row=e.target.closest('[data-select-player]');if(row&&!e.target.matches('input,label,select,option')){state.selected={team:row.dataset.team,playerId:row.dataset.selectPlayer};render();return;}const action=e.target.closest('[data-action]');if(action&&selectedPlayer()){setActiveStatButton(action);addEvent(state.selected.team,state.selected.playerId,action.dataset.action);return;}const timeout=e.target.closest('[data-timeout]');if(timeout){byId('timeoutDialog').close();addEvent(timeout.dataset.timeout,null,'TIMEOUT');return;}const add=e.target.closest('[data-add-player]');if(add){const list=state[`players${add.dataset.addPlayer}`];if(list.length>=15)return showToast('選手は15名まで登録できます');list.push(normalizePlayer({id:`p-${Date.now()}-${Math.random()}`,number:'',name:'NEW PLAYER'}));render();}});
 document.addEventListener('input',e=>{const teamName=e.target.dataset.teamName;if(teamName){state[`team${teamName}Name`]=e.target.value;render();return;}const f=e.target.dataset.playerField;if(f){state[`players${e.target.dataset.team}`][+e.target.dataset.index][f]=e.target.value.replace(f==='license'?/\D/g:/(?!)/g,'').slice(0,f==='license'?3:999);saveState();return;}if(e.target.dataset.meta){state[e.target.dataset.meta]=e.target.value;saveState();return;}if(['tournament','gameDate'].includes(e.target.id)){state[e.target.id]=e.target.value;render();}});document.addEventListener('change',e=>{if(e.target.dataset.periodPlayer){state[`players${e.target.dataset.team}`][+e.target.dataset.index].periods[+e.target.dataset.periodPlayer-1]=e.target.value||null;render();}});
 byId('timeoutButton').onclick=()=>{byId('timeoutTeamA').textContent=state.teamAName;byId('timeoutTeamB').textContent=state.teamBName;byId('timeoutDialog').showModal();};
 function applyPeriodEvent(event,forward){state.running=false;clearInterval(timerId);state.period=forward?event.toPeriod:event.fromPeriod;state.seconds=forward?event.toSeconds:event.fromSeconds;}
 byId('undoButton').onclick=()=>{if(state.events.length){const event=state.events.pop();if(event.action==='PERIOD_CHANGE')applyPeriodEvent(event,false);state.future.push(event);render();}};
 byId('redoButton').onclick=()=>{if(state.future.length){const event=state.future.pop();if(event.action==='PERIOD_CHANGE')applyPeriodEvent(event,true);state.events.push(event);render();}};
 byId('periodAdvance').onclick=()=>{const current=periodLabel(state.period),next=periodLabel(state.period+1);byId('periodDialogTitle').textContent=state.period===4?'4Qを終了して延長へ進みますか？':`${current}を終了して${next}へ進みますか？`;byId('periodConfirm').textContent=`${next}へ進む`;byId('periodDialog').showModal();};
 byId('periodConfirm').onclick=()=>{const event=createPeriodChangeEvent(state);state.events.push(event);state.future=[];applyPeriodEvent(event,true);byId('periodDialog').close();render();};
 function applySheetZoom(mode=sheetZoomMode){sheetZoomMode=mode;const viewport=byId('sheetViewport'),stage=byId('sheetStage'),page=byId('scoreSheet');if(!viewport||!stage||!page)return;const pageWidth=page.offsetWidth,pageHeight=page.offsetHeight;if(!pageWidth||!pageHeight)return;const availableWidth=Math.max(0,stage.clientWidth-24),landscape=window.matchMedia('(orientation: landscape)').matches,availableHeight=landscape?Math.max(0,stage.clientHeight-12):pageHeight;const fitScale=Math.min(1,availableWidth/pageWidth,availableHeight/pageHeight);const scale=mode==='zoom'?1:fitScale;viewport.classList.toggle('zoom-fit',mode==='fit');viewport.classList.toggle('zoom-in',mode==='zoom');viewport.style.setProperty('--sheet-scale',String(scale));viewport.style.width=`${pageWidth*scale}px`;viewport.style.height=`${pageHeight*scale}px`;byId('fitButton').setAttribute('aria-pressed',String(mode==='fit'));byId('zoomButton').setAttribute('aria-pressed',String(mode==='zoom'));}
 byId('clockToggle').onclick=()=>{state.running=!state.running;if(state.running)timerId=setInterval(()=>{state.seconds=Math.max(0,state.seconds-1);if(!state.seconds){state.running=false;clearInterval(timerId);if(state.period>=4&&!state.endTime)state.endTime=new Date().toTimeString().slice(0,5);showToast('クォーター終了');}render();},1000);else clearInterval(timerId);render();};byId('clockReset').onclick=()=>{state.running=false;clearInterval(timerId);state.seconds=state.period<=4?360:180;render();};document.querySelectorAll('[data-possession]').forEach(b=>b.onclick=()=>{state.possession=b.dataset.possession;render();});byId('resetButton').onclick=()=>{if(confirm('この試合のすべての記録をリセットしますか？')){clearInterval(timerId);state=defaultState();render();showToast('試合をリセットしました');}};byId('printButton').onclick=()=>window.print();byId('fitButton').onclick=()=>applySheetZoom('fit');byId('zoomButton').onclick=()=>applySheetZoom('zoom');window.addEventListener('resize',()=>applySheetZoom());
 function parseVoice(text){const x=text.replace(/\s/g,'').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-65248)),n=x.match(/(\d+)番/)?.[1],map=[[/ディフェンスリバウンド|DREB/i,'DREB'],[/オフェンスリバウンド|OREB/i,'OREB'],[/アシスト/,'AST'],[/ターンオーバー/,'TOV'],[/スティール/,'STL'],[/ブロック/,'BLK'],[/ファウル/,'PF'],[/3点/,'3PM'],[/2点/,'2PM'],[/1点|フリースロー/,'FTM']],action=map.find(([r])=>r.test(x))?.[1];if(!n||!action)return null;let team=state.selected?.team,player=team&&state[`players${team}`].find(p=>p.number===n);if(!player){const hits=['A','B'].flatMap(t=>state[`players${t}`].filter(p=>p.number===n).map(player=>({team:t,player})));if(hits.length===1)({team,player}=hits[0]);}return player?{team,playerId:player.id,action}:null;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR();recognition.lang='ja-JP';recognition.interimResults=false;recognition.onresult=e=>{const text=e.results[0][0].transcript,p=parseVoice(text);byId('voiceStatus').textContent=`認識: ${text}`;if(p){state.selected={team:p.team,playerId:p.playerId};addEvent(p.team,p.playerId,p.action);}else showToast('選手番号またはプレイを認識できませんでした');};recognition.onerror=()=>showToast('音声を認識できませんでした');}else byId('voiceButton').disabled=true;byId('voiceButton').onclick=()=>{if(recognition){byId('voiceStatus').textContent='聞き取り中…';recognition.start();}};render();requestAnimationFrame(()=>applySheetZoom());
}
