const STORAGE_KEY = 'mini-basketball-scorebook-v3';
const ACTIONS = {
  FTM:{label:'FT成功',points:1},FTX:{label:'FT失敗',points:0},'2PM':{label:'2P成功',points:2},'2PX':{label:'2P失敗',points:0},'3PM':{label:'3P成功',points:3},'3PX':{label:'3P失敗',points:0},
  OREB:{label:'オフェンスリバウンド',points:0},DREB:{label:'ディフェンスリバウンド',points:0},AST:{label:'アシスト',points:0},TOV:{label:'ターンオーバー',points:0},STL:{label:'スティール',points:0},BLK:{label:'ブロック',points:0},PF:{label:'ファウル',points:0},TIMEOUT:{label:'タイムアウト',points:0}
};
const initialPlayers=()=>Array.from({length:5},(_,i)=>({id:`p-${i+1}-${Math.random().toString(36).slice(2)}`,number:String(i+4),name:`PLAYER ${i+1}`,license:'',periods:[false,false,false,false]}));
const defaultState=()=>({version:3,period:1,seconds:360,running:false,possession:null,selected:null,tournament:'U12 SPRING CUP',gameDate:new Date().toISOString().slice(0,10),gameTime:'',venue:'',gameNo:'',crewChief:'',umpire:'',scorer:'',timer:'',assistantScorer:'',shotClockOperator:'',endTime:'',playersA:initialPlayers(),playersB:initialPlayers(),teamAName:'SKY HAWKS',teamBName:'RED COMETS',teamAColor:'白',teamBColor:'',coachA:'',assistantCoachA:'',coachB:'',assistantCoachB:'',events:[],future:[],activeView:'input'});
function createEvent(state,team,playerId,action,id=`${Date.now()}-${Math.random()}`){if(!ACTIONS[action]||!['A','B'].includes(team))throw Error('Invalid event');if(action!=='TIMEOUT'&&!state[`players${team}`].some(p=>p.id===playerId))throw Error('Player not found');return{id,period:state.period,time:formatTime(state.seconds),team,playerId:playerId||null,action};}
function derive(state){
 const stats={A:{},B:{}},scores={A:0,B:0},quarterScores={A:[0,0,0,0,0],B:[0,0,0,0,0]},teamFoulsByPeriod={A:[0,0,0,0],B:[0,0,0,0]},timeouts={A:[0,0,0,0,0],B:[0,0,0,0,0]},running=[],pbp=[];let a=0,b=0;
 ['A','B'].forEach(t=>state[`players${t}`].forEach(p=>stats[t][p.id]={PTS:0,FTM:0,FTA:0,'2PM':0,'2PA':0,'3PM':0,'3PA':0,OREB:0,DREB:0,REB:0,AST:0,TOV:0,STL:0,BLK:0,PF:0}));
 state.events.forEach(event=>{const act=ACTIONS[event.action];if(!act)return;if(event.action==='TIMEOUT'){timeouts[event.team][Math.min(event.period,5)-1]++;pbp.push({...event,label:act.label,points:0,scoreA:a,scoreB:b});return;}const s=stats[event.team][event.playerId];if(!s)return;const points=act.points;
  if(event.action==='FTM'){s.FTM++;s.FTA++;}if(event.action==='FTX')s.FTA++;if(event.action==='2PM'){s['2PM']++;s['2PA']++;}if(event.action==='2PX')s['2PA']++;if(event.action==='3PM'){s['3PM']++;s['3PA']++;}if(event.action==='3PX')s['3PA']++;if(['OREB','DREB','AST','TOV','STL','BLK','PF'].includes(event.action))s[event.action]++;if(event.action==='PF'&&event.period<=4)teamFoulsByPeriod[event.team][event.period-1]++;
  s.PTS+=points;s.REB=s.OREB+s.DREB;scores[event.team]+=points;if(event.period<=5)quarterScores[event.team][event.period-1]+=points;if(event.team==='A')a+=points;else b+=points;const player=state[`players${event.team}`].find(p=>p.id===event.playerId);const detail={...event,player,label:act.label,points,scoreA:a,scoreB:b};pbp.push(detail);if(points)running.push(detail);
 });
 return{stats,scores,quarterScores,teamFoulsByPeriod,timeouts,running,pbp,teamFouls:{A:teamFoulsByPeriod.A[state.period-1]||0,B:teamFoulsByPeriod.B[state.period-1]||0}};
}
function formatTime(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}function periodLabel(p){return p<=4?`${p}Q`:'OT';}function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function runningScoreCells(data){const marks={A:{},B:{}};data.running.forEach(e=>{const end=e.team==='A'?e.scoreA:e.scoreB;for(let n=end-e.points+1;n<=end;n++)marks[e.team][n]={event:e,end:n===end};});return Array.from({length:3},(_,block)=>`<table class="run-block"><thead><tr><th>A</th><th></th><th>B</th></tr></thead><tbody>${Array.from({length:40},(_,i)=>{const n=block*40+i+1;return`<tr><td>${scoreMark(marks.A[n],n)}</td><th>${n}</th><td>${scoreMark(marks.B[n],n)}</td></tr>`}).join('')}</tbody></table>`).join('');}
function scoreMark(mark,n){if(!mark)return'';const cls=mark.event.action==='3PM'?'three':mark.event.action==='FTM'?'free':'field';return`<span class="score-mark ${cls} ${mark.end?'end':''}" title="${escapeHtml(mark.event.label)}">${mark.end?escapeHtml(mark.event.player.number):'／'}</span>`;}
if(typeof module!=='undefined')module.exports={ACTIONS,defaultState,createEvent,derive,formatTime,runningScoreCells};
if(typeof document!=='undefined'){
 let state=loadState(),timerId=null,recognition=null,zoomed=false;function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem('mini-basketball-scorebook-v2'));if(s)return{...defaultState(),...s,version:3,playersA:s.playersA.map(normalizePlayer),playersB:s.playersB.map(normalizePlayer),running:false};}catch{}return defaultState();}function normalizePlayer(p){return{license:'',periods:[false,false,false,false],...p};}function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,running:false}));}function byId(id){return document.getElementById(id);}function selectedPlayer(){return state.selected&&state[`players${state.selected.team}`].find(p=>p.id===state.selected.playerId);}function addEvent(team,id,action){state.events.push(createEvent(state,team,id,action));state.future=[];render();}
 function render(){const d=derive(state),p=selectedPlayer();byId('scoreA').value=d.scores.A;byId('scoreB').value=d.scores.B;byId('period').textContent=periodLabel(state.period);byId('clock').textContent=formatTime(state.seconds);byId('clockToggle').textContent=state.running?'PAUSE':'START';['teamAName','teamBName','tournament','gameDate'].forEach(id=>{if(document.activeElement!==byId(id))byId(id).value=state[id];});byId('homeRosterTitle').textContent=state.teamAName;byId('awayRosterTitle').textContent=state.teamBName;byId('teamFoulA').value=d.teamFouls.A;byId('teamFoulB').value=d.teamFouls.B;byId('selectionPrompt').innerHTML=p?`<small>SELECTED PLAYER</small><strong>${state.selected.team==='A'?'HOME':'AWAY'} #${escapeHtml(p.number)} ${escapeHtml(p.name)}</strong>`:'<small>SELECTED PLAYER</small><strong>選手を選択してください</strong>';document.querySelectorAll('[data-action]').forEach(b=>b.disabled=!p);byId('undoButton').disabled=!state.events.length;byId('redoButton').disabled=!state.future.length;document.querySelectorAll('[data-possession]').forEach(b=>b.classList.toggle('active',b.dataset.possession===state.possession));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.activeView));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${state.activeView}View`));renderRoster('A',d);renderRoster('B',d);renderStats(d);renderSheet(d);renderPbp(d);saveState();}
 function renderRoster(t,d){byId(`roster${t}`).innerHTML=state[`players${t}`].map((p,i)=>`<div class="player-row ${state.selected?.playerId===p.id?'selected':''}" data-select-player="${p.id}" data-team="${t}"><input data-player-field="number" data-team="${t}" data-index="${i}" value="${escapeHtml(p.number)}" aria-label="背番号"><input data-player-field="name" data-team="${t}" data-index="${i}" value="${escapeHtml(p.name)}" aria-label="選手名"><b>${d.stats[t][p.id].PF}</b><div class="period-checks">${[1,2,3,4].map(q=>`<label><input type="checkbox" data-period-player="${q}" data-team="${t}" data-index="${i}" ${p.periods[q-1]?'checked':''}>${q}Q</label>`).join('')}</div></div>`).join('');}
 function statTable(t,d){return`<section class="stat-card"><h2><i>${t==='A'?'HOME':'AWAY'}</i> ${escapeHtml(state[`team${t}Name`])}</h2><div class="table-wrap"><table><thead><tr><th>NO.</th><th>PLAYER</th>${['PTS','FTM/A','2PM/A','3PM/A','OREB','DREB','REB','AST','TOV','STL','BLK','PF'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${state[`players${t}`].map(p=>{const s=d.stats[t][p.id];return`<tr><td>${escapeHtml(p.number)}</td><td>${escapeHtml(p.name)}</td><td>${s.PTS}</td><td>${s.FTM}/${s.FTA}</td><td>${s['2PM']}/${s['2PA']}</td><td>${s['3PM']}/${s['3PA']}</td>${['OREB','DREB','REB','AST','TOV','STL','BLK','PF'].map(k=>`<td>${s[k]}</td>`).join('')}</tr>`}).join('')}</tbody></table></div></section>`;}function renderStats(d){byId('statsContent').innerHTML=statTable('A',d)+statTable('B',d);}
 function timeoutBoxes(t,d){return ['①','②','③','④','OT'].map((label,i)=>`<span class="timeout-box ${d.timeouts[t][i]?'used':''}">${label}<i>${d.timeouts[t][i]||''}</i></span>`).join('');}
 function sheetTeam(t,d){const list=[...state[`players${t}`],...Array(Math.max(0,15-state[`players${t}`].length)).fill(null)];return`<section class="official-team"><div class="team-band"><b>チーム ${t}</b><strong>${escapeHtml(state[`team${t}Name`])}</strong><label>色<input data-meta="team${t}Color" value="${escapeHtml(state[`team${t}Color`])}"></label><div class="timeout-strip"><small>タイムアウト</small>${timeoutBoxes(t,d)}</div></div><table class="player-sheet"><thead><tr><th rowspan="2">No.</th><th rowspan="2">ライセンス<br>No.</th><th rowspan="2">選手氏名</th><th rowspan="2">背番号<br>No.</th><th colspan="4">出場時限</th><th colspan="5">ファウル</th></tr><tr>${[1,2,3,4].map(x=>`<th>${x}</th>`).join('')}${[1,2,3,4,5].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${list.map((p,i)=>`<tr><td>${i+1}</td><td>${p?`<input aria-label="${t} ${i+1}番 ライセンスNo." maxlength="3" inputmode="numeric" data-player-field="license" data-team="${t}" data-index="${i}" value="${escapeHtml(p.license)}">`:''}</td><td>${p?escapeHtml(p.name):''}</td><td>${p?escapeHtml(p.number):''}</td>${[0,1,2,3].map(q=>`<td>${p?.periods[q]?'✓':''}</td>`).join('')}${[1,2,3,4,5].map(n=>`<td>${p&&d.stats[t][p.id].PF>=n?`<b class="foul-mark">×</b>`:''}</td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr><th colspan="2">コーチ</th><td colspan="5">${metaInput(`coach${t}`,'')}</td><th colspan="2">A.コーチ</th><td colspan="4">${metaInput(`assistantCoach${t}`,'')}</td></tr></tfoot></table></section>`;}
 function teamFoulPanel(t,d){return`<section class="foul-panel"><h3>チーム${t}<br>ファウル</h3>${[[0,1],[2,3]].map(pair=>`<div class="foul-pair"><div class="foul-quarter-head"><b>${pair[0]+1}Q</b><b>${pair[1]+1}Q</b></div>${[1,2,3,4].map(n=>`<div class="foul-row"><span class="${d.teamFoulsByPeriod[t][pair[0]]>=n?'marked':''}">${n}</span><span class="${d.teamFoulsByPeriod[t][pair[1]]>=n?'marked':''}">${n}</span></div>`).join('')}</div>`).join('')}</section>`;}
 function metaInput(key,label,type='text'){return`<label>${label}<input type="${type}" data-meta="${key}" value="${escapeHtml(state[key])}"></label>`;}
 function renderSheet(d){const winner=d.scores.A===d.scores.B?'引き分け':state[d.scores.A>d.scores.B?'teamAName':'teamBName'];byId('scoreSheet').innerHTML=`<header class="official-title"><b>JBA U12</b><h1>MINI-BASKETBALL OFFICIAL SCORESHEET</h1></header><section class="official-meta"><div class="competition-box">${metaInput('tournament','大会名')}</div><div class="score-summary"><div class="score-team-box"><small>チーム A</small><span>${escapeHtml(state.teamAName)}</span><strong>${d.scores.A}</strong></div><b class="score-dash">－</b><div class="score-team-box"><small>チーム B</small><span>${escapeHtml(state.teamBName)}</span><strong>${d.scores.B}</strong></div><div class="overtime-box">延長 <b>${d.quarterScores.A[4]}</b> － <b>${d.quarterScores.B[4]}</b></div></div><div class="match-meta">${metaInput('gameDate','日付','date')}${metaInput('gameTime','時間','time')}${metaInput('venue','会場')}${metaInput('gameNo','Game No.')}</div><div class="officials">${metaInput('crewChief','クルーチーフ')}${metaInput('umpire','アンパイア')}${metaInput('scorer','スコアラー')}${metaInput('timer','タイマー')}${metaInput('assistantScorer','A.スコアラー')}${metaInput('shotClockOperator','ショットクロックオペレーター')}</div></section><div class="sheet-body"><div class="teams-column">${sheetTeam('A',d)}${sheetTeam('B',d)}</div><div class="fouls-column">${teamFoulPanel('A',d)}${teamFoulPanel('B',d)}</div><section class="official-running"><h2>ランニングスコア</h2><div class="running-columns">${runningScoreCells(d)}</div></section></div><section class="result"><b>勝利チーム　<span>${escapeHtml(winner)}</span></b>${metaInput('endTime','試合終了時間','time')}</section><small class="sheet-note">ライセンスNo.：JBA登録番号（メンバーID）下3桁　　得点記号：2P ／・3P ○・FT ＿</small>`;}
 function renderPbp(d){byId('pbpContent').innerHTML=d.pbp.length?[...d.pbp].reverse().map(e=>`<article><time>${periodLabel(e.period)}<b>${e.time}</b></time><span class="team-badge ${e.team}">${e.team==='A'?'HOME':'AWAY'}</span><div><strong>${e.player?`#${escapeHtml(e.player.number)} ${escapeHtml(e.player.name)}`:'TEAM'}</strong><small>${e.label}</small></div><output>${e.scoreA} - ${e.scoreB}</output></article>`).join(''):'<div class="empty">まだ記録がありません</div>';}
 function showToast(m){const t=byId('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}document.addEventListener('click',e=>{const tab=e.target.closest('[data-view]');if(tab){state.activeView=tab.dataset.view;render();return;}const row=e.target.closest('[data-select-player]');if(row&&!e.target.matches('input,label')){state.selected={team:row.dataset.team,playerId:row.dataset.selectPlayer};render();return;}const action=e.target.closest('[data-action]');if(action&&selectedPlayer()){addEvent(state.selected.team,state.selected.playerId,action.dataset.action);return;}const timeout=e.target.closest('[data-timeout]');if(timeout){addEvent(timeout.dataset.timeout,null,'TIMEOUT');return;}const add=e.target.closest('[data-add-player]');if(add){const list=state[`players${add.dataset.addPlayer}`];if(list.length>=15)return showToast('選手は15名まで登録できます');list.push(normalizePlayer({id:`p-${Date.now()}-${Math.random()}`,number:'',name:'NEW PLAYER'}));render();}});
 document.addEventListener('input',e=>{const f=e.target.dataset.playerField;if(f){state[`players${e.target.dataset.team}`][+e.target.dataset.index][f]=e.target.value.replace(f==='license'?/\D/g:/(?!)/g,'').slice(0,f==='license'?3:999);saveState();return;}if(e.target.dataset.meta){state[e.target.dataset.meta]=e.target.value;saveState();return;}if(['tournament','gameDate','teamAName','teamBName'].includes(e.target.id)){state[e.target.id]=e.target.value;render();}});document.addEventListener('change',e=>{if(e.target.dataset.periodPlayer){state[`players${e.target.dataset.team}`][+e.target.dataset.index].periods[+e.target.dataset.periodPlayer-1]=e.target.checked;render();}});
 byId('undoButton').onclick=()=>{if(state.events.length){state.future.push(state.events.pop());render();}};byId('redoButton').onclick=()=>{if(state.future.length){state.events.push(state.future.pop());render();}};function changePeriod(n){const next=Math.max(1,Math.min(5,state.period+n));if(next===state.period)return;state.running=false;clearInterval(timerId);state.period=next;state.seconds=next<=4?360:180;render();}byId('periodDown').onclick=()=>changePeriod(-1);byId('periodUp').onclick=()=>changePeriod(1);byId('clockToggle').onclick=()=>{state.running=!state.running;if(state.running)timerId=setInterval(()=>{state.seconds=Math.max(0,state.seconds-1);if(!state.seconds){state.running=false;clearInterval(timerId);if(state.period>=4&&!state.endTime)state.endTime=new Date().toTimeString().slice(0,5);showToast('クォーター終了');}render();},1000);else clearInterval(timerId);render();};byId('clockReset').onclick=()=>{state.running=false;clearInterval(timerId);state.seconds=state.period<=4?360:180;render();};document.querySelectorAll('[data-possession]').forEach(b=>b.onclick=()=>{state.possession=b.dataset.possession;render();});byId('resetButton').onclick=()=>{if(confirm('この試合のすべての記録をリセットしますか？')){clearInterval(timerId);state=defaultState();render();showToast('試合をリセットしました');}};byId('printButton').onclick=()=>window.print();byId('fitButton').onclick=()=>{zoomed=false;byId('scoreSheet').classList.remove('zoomed');};byId('zoomButton').onclick=()=>{zoomed=!zoomed;byId('scoreSheet').classList.toggle('zoomed',zoomed);};
 function parseVoice(text){const x=text.replace(/\s/g,'').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-65248)),n=x.match(/(\d+)番/)?.[1],map=[[/ディフェンスリバウンド|DREB/i,'DREB'],[/オフェンスリバウンド|OREB/i,'OREB'],[/アシスト/,'AST'],[/ターンオーバー/,'TOV'],[/スティール/,'STL'],[/ブロック/,'BLK'],[/ファウル/,'PF'],[/3点/,'3PM'],[/2点/,'2PM'],[/1点|フリースロー/,'FTM']],action=map.find(([r])=>r.test(x))?.[1];if(!n||!action)return null;let team=state.selected?.team,player=team&&state[`players${team}`].find(p=>p.number===n);if(!player){const hits=['A','B'].flatMap(t=>state[`players${t}`].filter(p=>p.number===n).map(player=>({team:t,player})));if(hits.length===1)({team,player}=hits[0]);}return player?{team,playerId:player.id,action}:null;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR();recognition.lang='ja-JP';recognition.interimResults=false;recognition.onresult=e=>{const text=e.results[0][0].transcript,p=parseVoice(text);byId('voiceStatus').textContent=`認識: ${text}`;if(p){state.selected={team:p.team,playerId:p.playerId};addEvent(p.team,p.playerId,p.action);}else showToast('選手番号またはプレイを認識できませんでした');};recognition.onerror=()=>showToast('音声を認識できませんでした');}else byId('voiceButton').disabled=true;byId('voiceButton').onclick=()=>{if(recognition){byId('voiceStatus').textContent='聞き取り中…';recognition.start();}};render();
}
